### ISSUE TITLE
Overly broad error catching.

### ISSUE THREAD

**Issue by Carreau** [napari/npe2#13]
In this function the error catching is overly broad, any other error appear in the CLI as ``Could not find manifest for 'npe2_tester' as either a package name or a file``, hiding potential bugs in npe2 tester. I think we should be more restrictive into both what we catch, and/or raise a more narrow exception (maybe custom exceptions? )
```python
def _from_package_or_name(
        cls, package_or_filename: Union[Path, str]
    ) -> PluginManifest:
        
        try:
            return PluginManifest.from_file(package_or_filename)
        except ValidationError:
            raise
        except (FileNotFoundError, ValueError):
            try:
                return PluginManifest.from_distribution(str(package_or_filename))
            except ValidationError:
                raise
            except Exception as e:
                raise ValueError(
                    f"Could not find manifest for {package_or_filename!r} as either a "
                    "package name or a file.."
                ) from e

```

**Comment by tlambert03** [comment]
sure, makes sense..  remind me, what are the non-ValidationError errors that can happen here if the manifest is indeed found?
