### ISSUE TITLE
Add more maintainers on PyPI. 

### ISSUE THREAD

**Issue by Carreau** [napari/npe2#148]
And have a good process for release.

**Comment by tlambert03** [comment]
volunteering?

**Comment by Carreau** [comment]
Sure. 

@nclack ?

I feel like @jni and @sofroniewn should probably have publish rights as well ?

**Comment by Carreau** [comment]
and I'm `@mbussonn` on Pypi.

**Comment by Carreau** [comment]
We likely want to do a release to do a release soon to fix the napari/napari CI.

**Comment by tlambert03** [comment]
the pypi maintainers don't really matter right? ... all that matters is that someone can push a tag to github

**Comment by tlambert03** [comment]
yeah, I know... that's what #146 and #145  were for

**Comment by tlambert03** [comment]
added

**Comment by Carreau** [comment]
> the pypi maintainers don't really matter right? ... all that matters is that someone can push a tag to this repo, then the repo will publish to pypi

Ah ok, I was unsure about that. I guess just in case you need to yank, or anything else goes wrong, it's good to not have just you :-)
