### ISSUE TITLE
Release 0.3.0 final ?

### ISSUE THREAD

**Issue by Carreau** [napari/npe2#152]
With the release of 0.3.0rc0, the --pre test of napari started to pass: 

https://github.com/napari/napari/actions/workflows/test_prereleases.yml

I've closed https://github.com/napari/napari/issues/2481 so a similar issue will be created if tests fail again. 

I think we should be able to publish 0.3.0 final.

**Comment by tlambert03** [comment]
thanks @Carreau!  I just pushed a new tag
