### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/npe2#157]
### Description

Hi all,

I'm trying to find documentation for the npe2 yaml format. Is there some page listing what the entries mean? For example, there are multiple entries "display-name" [1](https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/napari.yaml#L2) [2](https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/napari.yaml#L43) and I'm wondering where this thing is displayed. Also how is [title](https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/napari.yaml#L10) different from display-name? Where is the title shown?

The format of [python-name](https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/napari.yaml#L12) would deserve a description for people who write their first npe2-based plugin.

I'm aware of the [transition guide](https://napari.org/plugins/npe2_migration_guide.html?highlight=npe2) but this document is not useful for beginners who start with npe2 and have never programmed a plugin using npe1.

Big thanks!
Robert

### What I Did
I googled ["napari npe2"](https://www.google.com/search?q=napari+npe2&oq=napari+npe2) and also [searched the napari documentation](https://napari.org/search.html?q=npe2) and couldn't find such a document.

**Comment by DragaDoncila** [comment]
@haesleinhuepf it sounds like you might be looking for the [manifest reference](https://napari.org/plugins/manifest.html) and [contributions reference](https://napari.org/plugins/contributions.html)? Let us know if that's not what you're after, or if it is, where you think it can be improved! 

I'm not sure why that didn't come up on a search, I would expect it to. We should also link to these documents from the migration guide, if we don't already.

**Comment by haesleinhuepf** [comment]
Thanks for the lightspeed response @DragaDoncila ! That's what I was searching.

> . We should also link to these documents from the migration guide, if we don't already.

Can you please also put a link in the npe2 repo readme?

Big thanks! 🌻
