### ISSUE TITLE
`filename_patterns` for readers should be case insensitive

### ISSUE THREAD

**Issue by DragaDoncila** [napari/npe2#271]
### Description

Currently our filename matching for readers is case sensitive (as evidenced below). I did a quick Google on what's good practice but I couldn't find a silver bullet "they should/shouldn't be" case sensitive. This current behaviour, however, is incompatible with `napari`'s behaviour which as of [#5121](https://github.com/napari/napari/pull/5121) lowercases filenames. 

If we agree that the patterns should be case insensitive, we should update the `iter_compatible_readers` check and the documentation.

Otherwise we should revert napari #5121? I don't think we can do one and not the other.
 
```python
In [20]: from npe2 import PluginManager, DynamicPlugin

In [21]: pm = PluginManager()

In [22]: reader_plugin = DynamicPlugin(name='tif_reader', plugin_manager=pm)

In [23]: @reader_plugin.contribute.reader(filename_patterns=["*.TIF"], accepts_directories=False)
    ...: def get_reader(path):
    ...:     def read(path):
    ...:         return [(None,)]
    ...:     return read
    ...: 

In [24]: pm.register(reader_plugin.manifest)

In [25]: list(pm.iter_compatible_readers("myfile.TIF"))
Out[25]: [ReaderContribution(command='tif_reader.get_reader', filename_patterns=['*.TIF'], accepts_directories=False)]

In [26]: list(pm.iter_compatible_readers("myfile.tif"))
Out[26]: []

```

**Comment by nclack** [comment]
Looks like there's some support for case-insensitive in this [zulip thread](https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/case.20insensitive.20pattern.20matching.3F).  I also like it - it's the default behavior I think folks will expect.

There's a risk that some reader might _need_ case-sensitive. But we can add a flag to the `ReaderContribution` to support that use case when it crops up.

Does anyone know of case-sensitive use cases?

**Comment by psobolewskiPhD** [comment]
Note that that napari PR only lower cases when checking for plugins, so it's the worst of both worlds 🤣 
See: https://github.com/napari/napari/issues/5663#issuecomment-1481886108
I don't think anyone would expect a different plugin for .jpg and .JPG so I think making everything case insensitive is the way to go.
So the question is just where is the best place to add the `.lower()`...

**Comment by nclack** [comment]
Looks like we have consensus on the _should_ so I changed the title of the issue (I hope that was alright).
