### ISSUE TITLE
pytomlpp dependecny make it hard to install on aarch64 (e.g docker for mac).

### ISSUE THREAD

**Issue by Carreau** [napari/npe2#291]
* npe2 version: stable/latest
* Python version: 3.10/3.11
* Operating System: Mac/Linux

### Description

pytomlpp does not have either conda, or wheels for aarch64.

### What I Did

```
$ docker run -i -t continuumio/miniconda3 /bin/bash
$ pip install pytomlpp # or conda-install ... fails.
```

It's possible to install if you 1) create an env that install conda-forge `compilers`, and pip install to build it.

### suggestion

- Use fallback toml library and make pytomlpp optional when possible ?
- See if upstream can build wheels ?

**Comment by psobolewskiPhD** [comment]
On arm64 macOS there do appear to be conda-forge packages:
`mamba repoquery search pytomlpp`
```
 pytomlpp 1.0.13  py310h2887b22_0 conda-forge/osx-arm64
 pytomlpp 1.0.13  py311hd6ee22a_0 conda-forge/osx-arm64
...
...
```

**Comment by Carreau** [comment]
Yep on MacOs, but docker-on-mac will need a linux wheel.
I'm going to guess some linux users with AMD CPU might be affected as well ?

I wrote `Operating System: Mac/Linux` as I was unsure how this should be interpreted. I would have actually expected the docker images to ask for a linux-arm64 but they do pull manylinux_2_28_aarch64.whl

**Comment by tlambert03** [comment]
Really, it's such a minor thing, should have just used tomli to begin with.
