### ISSUE TITLE
Switch from `tolm` to `tomli`or `rtoml`

### ISSUE THREAD

**Issue by Czaki** [napari/npe2#30]
### Description
Maybe following  decision in `cibuildwheel` there should be change from `toml` to `tomli` or mayby `rtoml` even to get performance gain as parsing manifest will be important part of every napari start?

https://pypi.org/project/tomli/
https://pypi.org/project/rtoml/
https://github.com/pypa/cibuildwheel/issues/534

**Comment by tlambert03** [comment]
I'd be inclined to use `rtoml`, based on benchmarks, and general liking the author's other work.  But it's not on conda-forge (so we'd need to get it there before napari could depend on npe2).  That's not something I really want to take on at the moment, so `pytomlpp` presents a similar benchmark... with tomli significantly slower.  Thoughts on `pytomlpp`?
