### ISSUE TITLE
Typo in `_dynamic_plugin.py`

### ISSUE THREAD

**Issue by lucyleeow** [napari/npe2#303]
### Description

Confusing typo, probably copy paste error, here:

https://github.com/napari/npe2/blob/31d1c901c82e1a686c76a91b076f072b08f1b4f5/src/npe2/_dynamic_plugin.py#L92-L93

**Comment by tlambert03** [comment]
Lol.  Yep... would you mind opening a PR to correct it?  Doesn't need to say anything fancy, just a basic "register plugin"
