### ISSUE TITLE
release npe2 0.7.1?

### ISSUE THREAD

**Issue by JoOkuma** [napari/npe2#305]
Hi, would it be possible to make a new release?

We need #292 which was recently merged to pass the napari/napari#5861 tests.

Thanks,

**Comment by tlambert03** [comment]
I'm not sure who's in charge of releases here now.  https://github.com/napari/npe2/actions/runs/5568717618

but I just pushed a release for you.  Would be good to have someone else paying attention to this repo going forward though

**Comment by JoOkuma** [comment]
Thanks @tlambert03 🙏
