### ISSUE TITLE
support for enabling/disabling a plugin

### ISSUE THREAD

**Issue by nclack** [napari/npe2#36]
napari's plugin install dialog allows plugins to be:

* enabled/disabled
* installed/uninstalled

~I believe (un)install can be handled entirely on the napari side. When a plugin is uninstalled, I think we require napari to be restarted for the changes to take effect. That system should work for npe2 plugins as well.~

However, some functionality should be added to npe2 to support enable/disable.

Some requirements:
- it should be possible to get a list of all plugins that includes both the enabled and disabled 
- iter_compatible_* functions should omit disabled plugins
- deactivate() should be invoked for plugins transitioning from the enabled to disabled state

I would love thoughts and input on the requirements. The description of this issue can be updated to keep them accurate.

#### Reference: Napari plugin install dialog
<img width="861" alt="Screen Shot 2021-11-23 at 12 11 35 PM" src="https://user-images.githubusercontent.com/98295/143097705-f635ef55-a656-42b9-a6b6-d005c4926666.png">

**Comment by tlambert03** [comment]
> I believe (un)install can be handled entirely on the napari side. When a plugin is uninstalled, I think we require napari to be restarted for the changes to take effect.

Actually no, restart is not required (at least we try not to make it required), and that should be the case in npe2 as well. 

We need a disabled list, and it needs to be restored from settings on startup (it should block addition of manifests from disabled plugins). 

We then need events to alert things like menus to remove items when disabled

**Comment by tlambert03** [comment]
Note, the plugin manager in napari is a subclass of the one in npe1, partially so that it can be evented

**Comment by nclack** [comment]
this was resolved in napari/napari#4086
