### ISSUE TITLE
CI failing due to test expecting package name with hyphens containing underscores instead

### ISSUE THREAD

**Issue by DragaDoncila** [napari/npe2#363]
### Description

See #362 for an example failure, but TLDR:

Our `test_fetch_npe1_manifest_with_sample_data` [test](https://github.com/napari/npe2/blob/main/tests/test_fetch.py#L37) expects `napari-pyclesperanto-assistant` to have hyphens in the name, but as of releasing v0.23.0 on October 18th, the package's metadata has underscores in the name.

The [package name](https://pypi.org/project/napari-pyclesperanto-assistant/#history) on `pypi` still has hyphens, even though [the package's setup.py](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/master/setup.py#L33) file has underscores. I think that's because of [PEP503](https://packaging.python.org/en/latest/specifications/name-normalization/), but either `setuptools_scm` or some other package in the middle is no longer normalizing names I guess?

None of this is super relevant to us I guess, except that I'm curious what's changed. Based on [this comment](https://github.com/napari/npe2/blob/main/src/npe2/manifest/schema.py#L95) in the schema, we are not normalizing package names for the manifest name, so the underscore is fine in that regard. It's just a little strange because it technically would no longer match the package name as it's listed on pypi - note though that `fetch_manifest` works if it's passed underscores **or** hyphens.

Is it fine to just change the test to use underscores? That's what I'm leaning towards here, but I'm not sure if there will be gotchas about this somewhere down the line... @jni @Czaki? We could also just use any of the other sample-data providing manifests and avoid this entirely!

**Comment by Czaki** [comment]
I do not know. I remember that `npe2` has big problems with `-` and `_` instead of normalizing it...
It was always a pain to fight with this, but I never dived into it, so I do not know the motivations.

**Comment by jni** [comment]
I would just change the line to:

```python
    assert mf.name.replace('_', '-') == "napari-pyclesperanto-assistant"
```

so it works in either scenario (if it changes back for whatever reason)

**Comment by DragaDoncila** [comment]
I actually think it's cleaner to just find another sample-data providing plugin and use that, so that's what I'll do to fix CI.

> I do not know. I remember that npe2 has big problems with - and _ instead of normalizing it...

Would be good if you could expand on this. As far as I can tell this is not an npe2 problem specifically - the downloaded wheel from pypi has a different package name to the pypi package name, which now matches the name listed in the package's `setup.py`. I agree we should probably normalize names to be compliant with PEP503, but this feels like an upstream issue to me.

**Comment by Czaki** [comment]
For pip `setuptools-scm` and `setuptools_scm` are equivalent.
