### ISSUE TITLE
rename `autogenerate_from_command` to `autogenerate`

### ISSUE THREAD

**Issue by nclack** [napari/npe2#53]
> `autogenerate_from_command` is a bit verbose, but hard to confuse :)

that's fine, but i would have suggested `autogenerate` as being clear in context and a little more friendly, unless you think we'd ever have other `autogenerate_from_....` fields, but those are likely to be incompatible with a bool on `autogenerate_from_command`

_Originally posted by @sofroniewn in https://github.com/napari/npe2/issues/51#issuecomment-990110114_

**Comment by nclack** [comment]
wanted to surface this comment as an issue for discussion. I'm happy to rename, but don't have particularly strong feelings.

**Comment by sofroniewn** [comment]
@tlambert03 @jni preference here? I don't want to trigger a big debate - but I do want some consideration. It's just way easier to change this right now instead of in 6 months.

**Comment by tlambert03** [comment]
Fine with me, don't have strong opinion.  I guess I'd abstain :). @jni? @nclack?

**Comment by jni** [comment]
I don't have full context here, but looking at the code line in #51 `command=cmd, ..., autogenerate_from_command=True`, I agree that `autogenerate=` reads better. So, mild in-favour of the rename.

**Comment by sofroniewn** [comment]
@nclack let's go with `autogenerate=` then. I have mild in-favor too, which seems to swing it. Thanks for the brief discussion on this
