### ISSUE TITLE
reconsidering `engine` name 

### ISSUE THREAD

**Issue by tlambert03** [napari/npe2#64]
hey @nclack ... I was looking at the vscode docs, and realized that they use "engine" to mean the version of _vscode_ that the package is targeting (not the version of the manifest).  On its own, I don't think "engine" is immediately obvious (though, perhaps someone could figure it out because it's called np**e**).  But, what would you think of using `schema_version` instead?  Hard to get that wrong

**Comment by nclack** [comment]
yeah that's better...
