### ISSUE TITLE
Task: help plugins maintain support for older versions of napari?

### ISSUE THREAD

**Issue by tlambert03** [napari/npe2#80]
even once napari adds npe2 to dependencies, plugins are going to have a tricky time supporting various napari versions unless we come up with a way to allow them to have both entry points.

I think this came up in the past and I suggested that plugins only implement one of the two entry points, but forgot that this means they will no longer be compatible with napari < 0.4.13.

I think this will require some communication between plugin managers.  Specifically, if npe2's plugin manager sees a plugin, npe1's plugin manager shouldn't register it.

**Comment by nclack** [comment]
Agree that this is an issue.

I kind of like the idea of putting npe2 in the driver's seat when it comes to plugin discovery. It could find all plugins with either entry point, and then supply the npe1-only list. The npe1 plugin_manager's iter_available() function would invoke npe2 to get the list. What do you think about that?

**Comment by tlambert03** [comment]
this is resolved
