### ISSUE TITLE
Entry points not always being parsed correctly from `setup.py`

### ISSUE THREAD

**Issue by DragaDoncila** [napari/npe2#93]
* npe2 version: npe2-0.1.2
* Python version: 3.9
* Operating System: macOS Big Sur

### Description

When trying to convert an npe1 plugin with a `setup.py` file, the entry point is being parsed as a list of lists, with each inner list being a letter. Inspecting `_entry_points` [here](https://github.com/napari/npe2/blob/0f2cec315be9efe4bfc185e9d051542621907095/npe2/_from_npe1.py#L534) while debugging gives:

```python
> _entry_points
[['S'], ['t'], ['a'], ['r'], ['D'], ['i'], ['s'], ['t'], [''], ['', ''], [''], ['s'], ['t'], ['a'], ...]
```

The process then terminates with

```python
Conversion failed:
ValueError: not enough values to unpack (expected 2, got 1)
```

based on the unpacking happening on [the next line](https://github.com/napari/npe2/blob/0f2cec315be9efe4bfc185e9d051542621907095/npe2/_from_npe1.py#L535)

### What I Did

```bash
pip install npe2
git clone https://github.com/stardist/stardist-napari.git
cd stardist-napari
pip install -e .
npe2 convert .
```

I'm not sure if this is a `stardist` specific issue or not (feel free to close if so)

**Comment by nclack** [comment]
In this case the problem was that the source `setup.py` had this line:

```python
entry_points={'napari.plugin': 'StarDist = stardist_napari'},
```

Using a list fixes things:

```python
entry_points={'napari.plugin': ['StarDist = stardist_napari']},
```

Is there a spec somewhere that says it should be a list?
